// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPB4h-grdTLbqAvJYVm76zv6YLmaK5TH0',
    appId: '1:564805172408:web:173f4eb45e03e8b1f0084d',
    messagingSenderId: '564805172408',
    projectId: 'appboline-ios-flu',
    authDomain: 'appboline-ios-flu.firebaseapp.com',
    storageBucket: 'appboline-ios-flu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0lDd-DbAt9skGN7v8EPU_TXZ0qYSyCaU',
    appId: '1:564805172408:android:ff832537bec6eccef0084d',
    messagingSenderId: '564805172408',
    projectId: 'appboline-ios-flu',
    storageBucket: 'appboline-ios-flu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVNoYgCVhh6hPL83C6nCeNaY--I8jlTIw',
    appId: '1:564805172408:ios:d86a5976b8b71ba0f0084d',
    messagingSenderId: '564805172408',
    projectId: 'appboline-ios-flu',
    storageBucket: 'appboline-ios-flu.appspot.com',
    iosClientId: '564805172408-d8nrjogkdur5s2k1qs002m7d8c9spjtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVNoYgCVhh6hPL83C6nCeNaY--I8jlTIw',
    appId: '1:564805172408:ios:d86a5976b8b71ba0f0084d',
    messagingSenderId: '564805172408',
    projectId: 'appboline-ios-flu',
    storageBucket: 'appboline-ios-flu.appspot.com',
    iosClientId: '564805172408-d8nrjogkdur5s2k1qs002m7d8c9spjtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
